sonar.projectKey=modul3-251511042
sonar.projectName=Modul 3 - 251511042 Immanoel
sonar.sources=app,routes,resources
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/build/**
sonar.sourceEncoding=UTF-8
